name: pipeline
on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/cblokkeel/geofight:latest
            ghcr.io/cblokkeel/geofight:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Docker stack deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: geofight 
          file: compose.prod.yaml
          host: cblokkeel.dev
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
          env_file: ./envfile

